name: 'Call workflow when file is pushed'

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://www.google.com/search?q=github'
        method: 'GET'
        username: ${{ secrets.AWX_USER }}
        password: ${{ secrets.AWX_PASSWORD }}
